hide-logo:
  variations:
    enabled: true
    disabled: false
  defaultRule:
    variation: disabled

title-flag:
  variations:
    default_title: GO Feature Flag
    developer_title: GOFF
  targeting:
    - query: userType eq "dev"
      variation: developer_title
  defaultRule:
    variation: default_title
  metadata:
    title: "Feature Flag Title"
    description: "This flag controls the title of the feature flag"

badge-class:
  variations:
    blue: badge-blue
    green: badge-green
    red: badge-red
    nocolor: ""
  defaultRule:
    variation: nocolor
  targeting:
    - query: userType eq "dev"
      variation: blue
    - query: userType eq "customer"
      variation: green
    - query: userType eq "admin"
      variation: red
