linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - revive
    - gosec
    - lll
    - misspell
    - nakedret
    - noctx
    - prealloc
    - rowserrcheck
    - exportloopref
    - stylecheck
    - unconvert
    - unparam
    - whitespace
#    - gofumpt
linters-settings:
  funlen:
    lines: 90
    statements: 50
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  golint:
    min-confidence: 0.6
  gosimple:
    checks: ["all","-S1023"]
  gofumpt:
    module-path: github.com/thomaspoignant/go-feature-flag
issues:
  exclude-dirs:
    - (^|/)bin($|/)
    - (^|/)examples($|/)
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
        - maligned
        - noctx
        - scopelint
        - bodyclose
        - lll
        - goconst
        - gocognit
        - gocyclo
        - gochecknoinits
        - dupl
        - staticcheck
        - revive
        - gosec
    - path: _mock.go
      linters:
        - funlen
        - maligned
        - noctx
        - scopelint
        - bodyclose
        - lll
        - goconst
        - gocognit
        - gocyclo
        - gochecknoinits
        - dupl
        - staticcheck
        - revive
