linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - revive
    - gosec
    - lll
    - misspell
    - nakedret
    - noctx
    - prealloc
    - rowserrcheck
    - copyloopvar
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - gofmt
    - gci
#    - gofumpt
linters-settings:
  funlen:
    lines: 90
    statements: 50
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  gosimple:
    checks: [ "all","-S1023" ]
  gofumpt:
    module-path: github.com/thomaspoignant/go-feature-flag
  gci:
    skip-generated: true
    no-lex-order: true
issues:
  exclude-dirs:
    - (^|/)bin($|/)
    - (^|/)examples($|/)
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
        - maligned
        - noctx
        - scopelint
        - bodyclose
        - lll
        - goconst
        - gocognit
        - gocyclo
        - gochecknoinits
        - dupl
        - staticcheck
        - revive
        - gosec
        - copyloopvar
    - path: _mock.go
      linters:
        - funlen
        - maligned
        - noctx
        - scopelint
        - bodyclose
        - lll
        - goconst
        - gocognit
        - gocyclo
        - gochecknoinits
        - dupl
        - staticcheck
        - revive
