before:
  hooks:
    - go mod tidy
    - go generate ./...

dist: release

builds:
#  - id: go-feature-flag-migration-cli
#    main: ./cmd/migrationcli
#    binary: go-feature-flag-migration-cli
#    env:
#      - CGO_ENABLED=0
#    goos:
#      - darwin
#      - linux
#      - windows
#    goarch:
#      - 386
#      - amd64
#      - arm64
#      - arm
#    goarm:
#      - 6
#      - 7
#    ignore:
#      - goos: darwin
#        goarch: 386
#      - goos: linux
#        goarch: arm
#        goarm: 6

  - id: go-feature-flag-relay-proxy
    main: ./cmd/relayproxy
    binary: go-feature-flag-relay-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
      - 8

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^testdata:'
      - '^.github'
      - '^examples'
      - 'vendor'

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    ids:
      - go-feature-flag-relay-proxy
    dockerfile: ./cmd/relayproxy/DockerfileGoreleaser
    image_templates:
      - thomaspoignant/test-repository:latest-amd64
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: arm64
    goarm: 8
    ids:
      - go-feature-flag-relay-proxy
    dockerfile: ./cmd/relayproxy/DockerfileGoreleaser
    image_templates:
      - thomaspoignant/test-repository:latest-arm64v8
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-arm64v8
    build_flag_templates:
      - "--platform=linux/arm64/v8"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    ids:
      - go-feature-flag-relay-proxy
    dockerfile: ./cmd/relayproxy/DockerfileGoreleaser
    image_templates:
      - thomaspoignant/test-repository:latest-armv7
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-armv7
    build_flag_templates:
      - "--platform=linux/arm/v7"
docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: thomaspoignant/test-repository:latest
    id: go-feature-flag-relay-proxy-latest
    image_templates:
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-arm64v8
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-armv7
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-amd64
  - name_template: thomaspoignant/go-feature-flag-lint:{{ .Tag }}
    id: go-feature-flag-relay-proxy-tag
    image_templates:
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-arm64v8
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-armv7
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-amd64
  - name_template: thomaspoignant/test-repository:v{{ .Major }}
    id: go-feature-flag-relay-proxy-major
    image_templates:
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-arm64v8
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-armv7
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-amd64
  - name_template: thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}
    id: go-feature-flag-relay-proxy-major-minor
    image_templates:
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-arm64v8
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-armv7
      - thomaspoignant/test-repository:v{{ .Major }}.{{ .Minor }}-amd64