before:
  hooks:
    - go mod tidy
    - go generate ./...

dist: release

builds:
  - id: go-feature-flag-migration-cli
    main: ./cmd/migrationcli
    binary: go-feature-flag-migration-cli
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 6

archives:
  - id: go-feature-flag-migration-cli
    builds:
      - go-feature-flag-migration-cli
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^testdata:'
      - '^.github'
      - '^examples'
      - 'vendor'

dockers:
  - goos: linux
    ids:
      - go-feature-flag-migration-cli
    dockerfile: ./cmd/migrationcli/Dockerfile
    image_templates:
      - thomaspoignant/go-feature-flag-migration-cli:latest
      - thomaspoignant/go-feature-flag-migration-cli:{{ .Tag }}
      - thomaspoignant/go-feature-flag-migration-cli:v{{ .Major }}
      - thomaspoignant/go-feature-flag-migration-cli:v{{ .Major }}.{{ .Minor }}

brews:
  - ids:
      - go-feature-flag-migration-cli
    name: go-feature-flag-migration-cli
    tap:
      owner: thomaspoignant
      name: homebrew-tap
    caveats: "A migration command line to move your feature flag configuration file from format GO Feature Flag v0.X to v1.X"
    homepage: "https://github.com/thomaspoignant/go-feature-flag/cmd/migrationcli"
    description: "A migration command line to move your feature flag configuration file from format GO Feature Flag v0.X to v1.X"
    skip_upload: auto

scoop:
  url_template: "https://github.com/thomaspoignant/go-feature-flag/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  bucket:
    owner: thomaspoignant
    name: scoop
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://gofeatureflag.org"
  license: MIT

snapshot:
  name_template: "{{ incpatch .Version }}-next"
