ignore:
  - "examples"
  - "testdata"
  - "testutils"
  - "website"
  - "modeldocs"
  - "**/_test.go"
  - "**/_mock.go"
  - "**/testdata/"
  - "**/testutils/"
  - "**/modeldocs/"
  - "cmd/relayproxy/docs/"
  - "cmd/jsonschema-generator/"
  - "cmd/relayproxy/modeldocs/"
