version: '3'

networks:
  apinet:
    driver: bridge

services:
  gofeatureflag:
    image: thomaspoignant/go-feature-flag
    ports:
      - "1031:1031"
    volumes:
      - type: bind
        source: ./
        target: /goff/
    networks:
      - apinet
  
  demo-app:
    build: nodejs-app/.
    networks:
      - apinet
    depends_on:
      - gofeatureflag