version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: make vendor
      - run: make lint
  test:
    docker:
      - image: circleci/golang:1.15
      working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
      steps:
        - checkout
        - run: make vendor
        - run: make test
        - run: make coverage
