version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: mkdir /tmp/test-results
      - run: make vendor
      - run: make lint
      - run: make test
      - run: make coverage
      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results
