apiVersion: v1
kind: Service
metadata:
  name: {{ include "relay-proxy.fullname" . }}
  labels:
    {{- include "relay-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if (include "relay-proxy.monitoringPort" .) }}
    - port: {{ include "relay-proxy.monitoringPort" . }}
      targetPort: monitoring
      protocol: TCP
      name: monitoring
    {{- end }}
  selector:
    {{- include "relay-proxy.selectorLabels" . | nindent 4 }}
