name: ↩ Change
description: Update functionality that already exists.
title: "(change) <title>"
labels: [change, needs-triage]
body:
  - type: textarea
    attributes:
      label: Motivation
      description: Give us information why do we need to change how it works.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Requirements
      description: What this change is supposed to do?
    validations:
      required: true
