name: ⚙️ Feature
description: Add new functionality to the project.
title: "(feature) <title>"
labels: [enhancement, needs-triage]
body:
  - type: textarea
    attributes:
      label: Requirements
      description: |
        Ask us what do you want!  
        Please provide us scenario file, logs or anything you have that can help us to understand.
    validations:
      required: true
