---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: goff-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: goff-sa
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: goff-sa
subjects:
  - kind: ServiceAccount
    name: goff-sa
roleRef:
  kind: ClusterRole
  name: goff-sa
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    app: goff-test-configmap
  name: goff-test-configmap
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: goff-test-configmap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: goff-test-configmap
    spec:
      containers:
      - image: goff-test-configmap:latest
        imagePullPolicy: Never
        name: goff-test-configmap
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: goff-sa
