# Use root/example as user/password credentials
version: '3.1'

services:
  postgres:
    container_name: goff_postgres
    hostname: postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=flags_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

  pgadmin:
    container_name: goff_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@example.com
      - PGADMIN_DEFAULT_PASSWORD=example
    ports:
      - "5050:80"

