name: Issue assignment

on:
  issues:
    types: [opened]
permissions: read-all

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Auto-assign issue"
        uses: pozil/auto-assign-issue@39c06395cbac76e79afc4ad4e5c5c6db6ecfdd2e # v2.2.0
        with:
          assignees: thomaspoignant
          numOfAssignee: 1
          allowSelfAssign: false
