name: "Brew"
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  homebrew:
    name: Bump homebrew-core formula
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.2

      - run: echo "${{ github.repository }}"

      - uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: go-feature-flag-relay-proxy
          tag-name: "v1.6.0"  # $GIT_TAG_NAME
          download-url: https://github.com/${{ github.repository }}.git
          commit-message: |
            {{formulaName}} {{version}}

            Version `{{version}}` of the go-feature-flag-relay-proxy is available.
            This PR bump the version in homebrew.

            Check https://gofeatureflag.org if you want to have more information about GO Feature Flag.

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
