name: Test_tag
on:
  release:
    types: [ published ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - run: echo ${GITHUB_REF}
        - run: echo ${{  github.ref_name }}
        - run: GIT_TAG_NAME=${{  github.ref_name }} && echo ${GIT_TAG_NAME#v}