name: Tmp Release
on:
  release:
    types: [ published ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  wasm-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.37.0'
      - run: ./.github/ci-scripts/release_wasm.sh ${{  github.ref_name }}
      - run: ls ./out/release-wasm