name: "Check all SDK versions and update the documentation"
on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  sdk-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          fetch-depth: 1
          persist-credentials: false
      - name: Setup go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: ./website/.ci/go.mod
          check-latest: true
          cache: false
      - run: go run ./website/.ci/sdkVersions.go
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          push_options: "--force"
          commit_message: "docs(website): update SDK versions"
